### ISSUE TITLE
Causes Duo Account Lockout.

### ISSUE THREAD

**Issue by miked97** [liuch/duolingo-scripts#1]
The DuoProfile script causes a temporary account lockout. It seems to load too many pages and cause a "too many requests" error. This is the same error that was supposedly fixed in another similar script. https://github.com/vaughanchandler/duolingo/issues/4

**Comment by liuch** [comment]
The DuoProfile script does not send any requests. It just handles some answers from the server. Why did you decided that it is the cause of this error?

**Comment by miked97** [comment]
It appears that I accidentally enabled a second script while enabling this one. Sorry about that!

**Comment by liuch** [comment]
That is alright. Good luck!
