### ISSUE TITLE
The script doesn't seem to work (for me) with the new version of the website.

### ISSUE THREAD

**Issue by graciecat** [liuch/duolingo-scripts#2]
Duolingo is switching, little by little, all users to a new version of the website.
Like almost all userscripts written for Duolingo, this one seems to not work anymore with the new version.

**Comment by liuch** [comment]
Yes, I know that. They made a lot of changes to the code. For now my account still has the old version. But I am going to create a new account to try to fit my scripts to the new code.

**Comment by Filip013** [comment]
Any news about this?

**Comment by haigha** [comment]
Thanks for posting this script.

Not working for me currently with Opera or Chrome (latest x64 versions on Windows 7).

The prompts for number of lingots and then confirmation occur but then nothing happens and no lingots are transferred.

**Comment by liuch** [comment]
I updated the script number minutes ago. Can you check its latest version (0.4.3)?

**Comment by haigha** [comment]
Much better, thanks! It looks like the total on the forum page is a little lower than I gave, but the amount given in the sender account matches the amount received.

I appreciate your efforts!

**Comment by liuch** [comment]
This is an old server-side bug that was brought with a new version of the forum about a year ago. See the comments [here](https://forum.duolingo.com/comment/24701177).The confusion with votes on the forum has the same roots. I cannot fix it.
