### ISSUE TITLE
[Request] DuoProfile show Learning from X to Y language

### ISSUE THREAD

**Issue by CeruleanSky** [liuch/duolingo-scripts#4]
I was wondering if it was possible to have the DuoProfile script show what language a person is learning from and to.

Some examples of what is desired:

English from Spanish
Japanese from English
Chinese from Japanese

Right now it just shows:
English
Japanese
Chinese

**Comment by liuch** [comment]
There is a problem here: If you learn one language from two others, your profile displays only one line with the target language. I'll think it over.

**Comment by CeruleanSky** [comment]
I suppose it would require duplicating the item then modifying it.  Don't worry about it if it is too much trouble.

Thank you for considering and thinking about it.

**Comment by liuch** [comment]
Implemented: https://github.com/liuch/duolingo-scripts/commit/00196d682322235336a3fe5102d770148fc0bc05. Just hover your mouse cursor on the course you need. Maybe I'll change this later if I come up with something better.

**Comment by CeruleanSky** [comment]
Thank you for implementing this, seems to work and looks nice.
