### ISSUE TITLE
Suggestion: DuoProfile - add info about User League

### ISSUE THREAD

**Issue by alexseyk** [liuch/duolingo-scripts#5]
Suggestion: DuoProfile - add info about User League

**Comment by liuch** [comment]
This is a great suggestion, but the server provides info about the User League only if you are this user or you are in the same set of League. If there is a way to get such info, I am not aware of. Do you know how to get this info?

**Comment by alexseyk** [comment]
I can see League info in the app on Android, so i just thought it might be  posible

**Comment by liuch** [comment]
Can you see League info for ANY user, even if the user is not in your league? Perhaps I misunderstood you, and you suggest adding information only to your own user's profile only. Can you explain your suggestion in more detail?

**Comment by alexseyk** [comment]
Ну да видно для любого пользователя
Но если Андройд видит, то может можно как то вытащить эту информаци и показывать ее через ваш скрипт ? 
<img width="492" alt="Screen Shot 2020-02-19 at 10 34 31" src="https://user-images.githubusercontent.com/60418150/74799658-b383fb80-5303-11ea-97e1-02ee45eb9476.png">

**Comment by liuch** [comment]
Спасибо за скриншот. Я не пользуюсь приложением, оттого не знал, что есть какое-то API для этого. То API, что используется в web-версии дуолинго, этого не позволяет - я проверял. Я постараюсь разобраться в этом. Еще раз спасибо.

**Comment by alexseyk** [comment]
FYI: duome.eu shows leagues now

**Comment by liuch** [comment]
Yes, I saw it yesterday. I will roll out an update within a couple of days.
