### ISSUE TITLE
Suggestion: Duo Forum Flags collapse & text

### ISSUE THREAD

**Issue by alexseyk** [liuch/duolingo-scripts#6]
Hello again

I think i came across a script that collapse flags on the forum that does not fit in one line.
May be you can point me in the right direction or write one ? 

Can you write a script that on mouse hove over the flag will show name of the corresponding country ? 
Thanks

**Comment by liuch** [comment]
Hello!

> I think i came across a script that collapse flags on the forum that does not fit in one line.
May be you can point me in the right direction or write one ?

DuoTweak did that. This script doesn't work anymore. I do not know other scripts that does the same, but I have never been iterested in this functionality.

> Can you write a script that on mouse hove over the flag will show name of the corresponding country ?

If I have spare time for that.
