### ISSUE TITLE
DuoProfile and preview.duolingo.com

### ISSUE THREAD

**Issue by Atervanda** [liuch/duolingo-scripts#9]
Hi,

Duolingo has recently released preview.duolingo.com for beta testers. Unfortunately, DuoProfile does not handle that site. Could you find a way to add it?

Thanks in advance!

**Comment by liuch** [comment]
I have just updated the script with bc263388d19db68d04c8f6994d29a7ce4e51086f. The script has supported this subdomain since version 1.5.1. Could you check it out?

**Comment by Atervanda** [comment]
Everything appears to be working fine. 👍 Спасибо!

**Comment by liuch** [comment]
Пожалуйста!
